const BRAND = 'ASTERA';
const TITLE_SUFFIX = ` – ${BRAND}`;

const FACEBOOK_URL = null;
const TWITTER_URL = null;
const LINKEDIN_URL = null;

const INDIEGOGO_URL = null;

const MAILCHIMP_API_KEY = 'e673ea4041cb728a90271e326ccb7659-us18'

const MAILCHAMP_API_LIST_KEY = '1063c251f8'

global.CONF = {
  BRAND, TITLE_SUFFIX,
  FACEBOOK_URL, TWITTER_URL, LINKEDIN_URL,
  INDIEGOGO_URL,MAILCHIMP_API_KEY
};
